# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 4.2

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/bin/cmake

# The command to remove a file.
RM = /usr/local/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/askdba/Documents/GitHub/myvector

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/askdba/Documents/GitHub/myvector

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/usr/local/Cellar/cmake/3.23.1/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/local/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/usr/local/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/usr/local/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/usr/local/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/usr/local/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/usr/local/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/usr/local/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/askdba/Documents/GitHub/myvector/CMakeFiles /Users/askdba/Documents/GitHub/myvector//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/askdba/Documents/GitHub/myvector/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named myvector_component

# Build rule for target.
myvector_component: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 myvector_component
.PHONY : myvector_component

# fast build rule for target.
myvector_component/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/myvector_component.dir/build.make CMakeFiles/myvector_component.dir/build
.PHONY : myvector_component/fast

src/component_src/myvector_binlog_service.o: src/component_src/myvector_binlog_service.cc.o
.PHONY : src/component_src/myvector_binlog_service.o

# target to build an object file
src/component_src/myvector_binlog_service.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/myvector_component.dir/build.make CMakeFiles/myvector_component.dir/src/component_src/myvector_binlog_service.cc.o
.PHONY : src/component_src/myvector_binlog_service.cc.o

src/component_src/myvector_binlog_service.i: src/component_src/myvector_binlog_service.cc.i
.PHONY : src/component_src/myvector_binlog_service.i

# target to preprocess a source file
src/component_src/myvector_binlog_service.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/myvector_component.dir/build.make CMakeFiles/myvector_component.dir/src/component_src/myvector_binlog_service.cc.i
.PHONY : src/component_src/myvector_binlog_service.cc.i

src/component_src/myvector_binlog_service.s: src/component_src/myvector_binlog_service.cc.s
.PHONY : src/component_src/myvector_binlog_service.s

# target to generate assembly for a file
src/component_src/myvector_binlog_service.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/myvector_component.dir/build.make CMakeFiles/myvector_component.dir/src/component_src/myvector_binlog_service.cc.s
.PHONY : src/component_src/myvector_binlog_service.cc.s

src/component_src/myvector_component.o: src/component_src/myvector_component.cc.o
.PHONY : src/component_src/myvector_component.o

# target to build an object file
src/component_src/myvector_component.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/myvector_component.dir/build.make CMakeFiles/myvector_component.dir/src/component_src/myvector_component.cc.o
.PHONY : src/component_src/myvector_component.cc.o

src/component_src/myvector_component.i: src/component_src/myvector_component.cc.i
.PHONY : src/component_src/myvector_component.i

# target to preprocess a source file
src/component_src/myvector_component.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/myvector_component.dir/build.make CMakeFiles/myvector_component.dir/src/component_src/myvector_component.cc.i
.PHONY : src/component_src/myvector_component.cc.i

src/component_src/myvector_component.s: src/component_src/myvector_component.cc.s
.PHONY : src/component_src/myvector_component.s

# target to generate assembly for a file
src/component_src/myvector_component.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/myvector_component.dir/build.make CMakeFiles/myvector_component.dir/src/component_src/myvector_component.cc.s
.PHONY : src/component_src/myvector_component.cc.s

src/component_src/myvector_component_config.o: src/component_src/myvector_component_config.cc.o
.PHONY : src/component_src/myvector_component_config.o

# target to build an object file
src/component_src/myvector_component_config.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/myvector_component.dir/build.make CMakeFiles/myvector_component.dir/src/component_src/myvector_component_config.cc.o
.PHONY : src/component_src/myvector_component_config.cc.o

src/component_src/myvector_component_config.i: src/component_src/myvector_component_config.cc.i
.PHONY : src/component_src/myvector_component_config.i

# target to preprocess a source file
src/component_src/myvector_component_config.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/myvector_component.dir/build.make CMakeFiles/myvector_component.dir/src/component_src/myvector_component_config.cc.i
.PHONY : src/component_src/myvector_component_config.cc.i

src/component_src/myvector_component_config.s: src/component_src/myvector_component_config.cc.s
.PHONY : src/component_src/myvector_component_config.s

# target to generate assembly for a file
src/component_src/myvector_component_config.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/myvector_component.dir/build.make CMakeFiles/myvector_component.dir/src/component_src/myvector_component_config.cc.s
.PHONY : src/component_src/myvector_component_config.cc.s

src/component_src/myvector_udf_service.o: src/component_src/myvector_udf_service.cc.o
.PHONY : src/component_src/myvector_udf_service.o

# target to build an object file
src/component_src/myvector_udf_service.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/myvector_component.dir/build.make CMakeFiles/myvector_component.dir/src/component_src/myvector_udf_service.cc.o
.PHONY : src/component_src/myvector_udf_service.cc.o

src/component_src/myvector_udf_service.i: src/component_src/myvector_udf_service.cc.i
.PHONY : src/component_src/myvector_udf_service.i

# target to preprocess a source file
src/component_src/myvector_udf_service.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/myvector_component.dir/build.make CMakeFiles/myvector_component.dir/src/component_src/myvector_udf_service.cc.i
.PHONY : src/component_src/myvector_udf_service.cc.i

src/component_src/myvector_udf_service.s: src/component_src/myvector_udf_service.cc.s
.PHONY : src/component_src/myvector_udf_service.s

# target to generate assembly for a file
src/component_src/myvector_udf_service.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/myvector_component.dir/build.make CMakeFiles/myvector_component.dir/src/component_src/myvector_udf_service.cc.s
.PHONY : src/component_src/myvector_udf_service.cc.s

src/myvector.o: src/myvector.cc.o
.PHONY : src/myvector.o

# target to build an object file
src/myvector.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/myvector_component.dir/build.make CMakeFiles/myvector_component.dir/src/myvector.cc.o
.PHONY : src/myvector.cc.o

src/myvector.i: src/myvector.cc.i
.PHONY : src/myvector.i

# target to preprocess a source file
src/myvector.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/myvector_component.dir/build.make CMakeFiles/myvector_component.dir/src/myvector.cc.i
.PHONY : src/myvector.cc.i

src/myvector.s: src/myvector.cc.s
.PHONY : src/myvector.s

# target to generate assembly for a file
src/myvector.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/myvector_component.dir/build.make CMakeFiles/myvector_component.dir/src/myvector.cc.s
.PHONY : src/myvector.cc.s

src/myvectorutils.o: src/myvectorutils.cc.o
.PHONY : src/myvectorutils.o

# target to build an object file
src/myvectorutils.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/myvector_component.dir/build.make CMakeFiles/myvector_component.dir/src/myvectorutils.cc.o
.PHONY : src/myvectorutils.cc.o

src/myvectorutils.i: src/myvectorutils.cc.i
.PHONY : src/myvectorutils.i

# target to preprocess a source file
src/myvectorutils.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/myvector_component.dir/build.make CMakeFiles/myvector_component.dir/src/myvectorutils.cc.i
.PHONY : src/myvectorutils.cc.i

src/myvectorutils.s: src/myvectorutils.cc.s
.PHONY : src/myvectorutils.s

# target to generate assembly for a file
src/myvectorutils.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/myvector_component.dir/build.make CMakeFiles/myvector_component.dir/src/myvectorutils.cc.s
.PHONY : src/myvectorutils.cc.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... myvector_component"
	@echo "... src/component_src/myvector_binlog_service.o"
	@echo "... src/component_src/myvector_binlog_service.i"
	@echo "... src/component_src/myvector_binlog_service.s"
	@echo "... src/component_src/myvector_component.o"
	@echo "... src/component_src/myvector_component.i"
	@echo "... src/component_src/myvector_component.s"
	@echo "... src/component_src/myvector_component_config.o"
	@echo "... src/component_src/myvector_component_config.i"
	@echo "... src/component_src/myvector_component_config.s"
	@echo "... src/component_src/myvector_udf_service.o"
	@echo "... src/component_src/myvector_udf_service.i"
	@echo "... src/component_src/myvector_udf_service.s"
	@echo "... src/myvector.o"
	@echo "... src/myvector.i"
	@echo "... src/myvector.s"
	@echo "... src/myvectorutils.o"
	@echo "... src/myvectorutils.i"
	@echo "... src/myvectorutils.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

