/* Build stub – not authoritative; generated by build scripts for standalone component build. */
#ifndef MY_CONFIG_INCLUDED
#define MY_CONFIG_INCLUDED

/* Leave empty; component build only needs the include to resolve. */

#endif /* MY_CONFIG_INCLUDED */
